inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
AllCops:
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'code-scanning-rubocop.gemspec'
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
