name: "Rubocop"

on: [push]

jobs:
  rubocop_job:
    runs-on: ubuntu-latest
    name: Code Scanning job run
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install Code Scanning integration
      run: bundle add code-scanning-rubocop --version 0.2.0 --skip-install

    - name: Install dependencies
      run: bundle install

    - name: Rubocop run
      run: bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: rubocop.sarif
